// src/features/auth/authSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Initial state with the token fetched from localStorage
const initialState = {
  token: localStorage.getItem("token") || null,
};

// Create slice with name 'auth', initial state, and reducers
const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    // loginUser reducer sets the token in the state
    loginUser: (state, action) => {
      state.token = action.payload;
    },
    // logoutUser reducer sets the token to null
    logoutUser: (state) => {
      state.token = null;
    },
  },
});

// Export actions (automatically generated by Redux Toolkit)
export const { loginUser, logoutUser } = authSlice.actions;

// Export the reducer to be used in the store
export default authSlice.reducer;
